### ISSUE TITLE
Faster Decryption

### ISSUE THREAD

**Issue by sam210723** [sam210723/COMS-1#10]
[xrit-decrypt.py](https://github.com/sam210723/COMS-1/blob/master/decrypt/xrit-decrypt.py) takes far too long to decrypt files. This is due to the slow pyDes library being used.

Needs an alternative implemented in either C or Golang.

**Comment by cql1983** [comment]
how about   pycrypto  ? or pycryptodome

**Comment by sam210723** [comment]
Fixed in 6f897e8 thanks to [cql1983](https://github.com/cql1983). Now using [```pycryptodome```](https://github.com/Legrandin/pycryptodome) instead of ```pyDes```. Decryption is now instant!
