### ISSUE TITLE
lrit-img.py  img  out-of-order

### ISSUE THREAD

**Issue by cql1983** [sam210723/COMS-1#11]
at my test, The resulting images are out of order
add  **files.sort()**

 `     30     # Check if input is a directory`
 `    31     if os.path.isdir(args.INPUT):`
`     32         # Loop through files with .lrit.dec extension in input folder`
`     33         for f in glob.glob(args.INPUT + "/*.lrit.dec"):`
`     34             files.append(f)`
`     35             files.sort()`
`     36 `
`     37         if files.__len__() <= 0:`
`     38             print("No LRIT files found")`
`     39             exit(1)`

the img okay.

**Comment by sam210723** [comment]
Are the image segments appearing out of order? Are you able to provide a sample image?

**Comment by cql1983** [comment]
use you IQ file test img  URL  https://raw.githubusercontent.com/cql1983/BI8AKT/master/docs/coms1(ubuntu16.04.6)-2019-07-07-13-13-03.png

**Comment by sam210723** [comment]
Ok I see. That's probably a Linux-specific issue. I'll make that change now.

**Comment by sam210723** [comment]
Working fine in my tests now. Could you please try this updated version?

**Comment by cql1983** [comment]
The latest code works, The image is normal.
